name: Build-Bounce-1.21
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21 # Minecraft 1.21 bat buoc dung Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Fix Permissions
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Bounce-1.21-Jar
          path: build/libs/*.jar
